### ISSUE TITLE
When deleting items from basket, the items are not disabled in the gui

### ISSUE THREAD

**Issue by skinkie** [StichtingOpenGeo-Museum/openebs#17]
Which results in a strange thing: if you again press nieuw bericht, it will not have all selected items anymore. This leads to the question if the the bag filling shouldn't occur at at pressing the nieuw bericht button.

**Comment by koch-t** [comment]
Is it possible to call a method when opening the nieuw bericht screen?

**Comment by skinkie** [comment]
$('#nieuwBerichtModal').on('show', function () {
  // do something…
})

**Comment by koch-t** [comment]
Fixed in 4d3036e2d707e6b6a3919564e110f7da6055e954
