### ISSUE TITLE
Clearly display the selected line

### ISSUE THREAD

**Issue by koch-t** [StichtingOpenGeo-Museum/openebs#18]
When using the line filter, clearly display something like "This is line 4"

**Comment by skinkie** [comment]
The selected number is now highlighted.

**Comment by koch-t** [comment]
Still confusing, that when you select a set of stops from the messages list, it still shows "Line x selected"

**Comment by koch-t** [comment]
And shouldn't "Alle lines be green as well"

**Comment by skinkie** [comment]
Maybe All lines should be "Alle haltes". Already fixed the messages case.
