### ISSUE TITLE
Geselecteerde cluster van features overleeft zoomen niet

### ISSUE THREAD

**Issue by skinkie** [StichtingOpenGeo-Museum/openebs#5]

**Comment by skinkie** [comment]
http://trac.osgeo.org/openlayers/ticket/3145

**Comment by koch-t** [comment]
http://openflights.org/blog/2009/10/21/customized-openlayers-cluster-strategies/

**Comment by koch-t** [comment]
Fixed in 8378db8cfc577fd3e69001922195f89c43e635db
